### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by Manghi**
Figured we should add this in to align with the rest of Conwayste.

### CODE REVIEW

**Comment by AaronM04** [comment]
Nice! But please also add the license messages at the top of the *.rs files. :)

**Review by AaronM04 — CHANGES_REQUESTED** [review]
license changes at top of src/*.rs files

**Comment by Manghi** [comment]
Thanks, done.

**Review by AaronM04 — APPROVED** [review]
Nice! :tada:

**Pull request merged**
